name: Demo CI/CD
on:
  push:
    branches:
      - 'demo'

  pull_request:
    branches:
      - 'demo'

env:
  CI: false
#   env_demo: ${{ secrets.ENV_DEMO }}

jobs:
  deploy:
    name: build docker image and push to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: demo

      #   - name: create environment file
      #     run: |
      #       touch ./.env && echo "$env_demo" >> ./.env

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push web
        id: build-push-web
        if: github.event_name == 'push'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false
          tags: esatya/rahat-frontend-web:demo

      - name: Build Docker image
        if: github.event_name == 'pull_request'
        run: docker build -t myimage:${{ github.sha }} .
